language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:

  # Prepare apt-get
  - sudo wget -O - http://debian.neo4j.org/neotechnology.gpg.key| sudo apt-key add -
  - echo 'deb http://debian.neo4j.org/repo stable/' | sudo tee -a /etc/apt/sources.list.d/neo4j.list
  - sudo apt-get update -qq

  # Prepare pip for httpie
  - sudo pip install --upgrade pip setuptools

  # Install Neo4J
  - sudo apt-get install -qq neo4j
  - sudo /etc/init.d/neo4j-service restart

  # Install HTTPie REST client and change the Neo4J password from the default to password
  - sudo pip install --upgrade httpie
  - sudo http -a neo4j:neo4j POST http://localhost:7474/user/neo4j/password password=password

# Install Composer an update dependencies
before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

# Run unit tests, with coveralls coverage
script:
  - mkdir -p coveralls                            # Make the coveralls directory
  - php vendor/bin/phpunit -c phpunit.xml         # Invoke PHPUnit with the right configuration file

# Upload to coveralls
after_script:
  - php vendor/bin/coveralls -c .coveralls.yml    # Invoke coveralls with the right configuration file.
